## Linear Regression

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('Customer_Churn.csv')

In [4]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [6]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors = 'coerce')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [8]:
df.shape

(7043, 21)

In [9]:
df.isna().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [10]:
df = df.dropna()

In [11]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [12]:
df.describe()

SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7032.000000  7032.000000     7032.000000   7032.000000
mean        0.162400    32.421786       64.798208   2283.300441
std         0.368844    24.545260       30.085974   2266.771362
min         0.000000     1.000000       18.250000     18.800000
25%         0.000000     9.000000       35.587500    401.450000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.862500   3794.737500
max         1.000000    72.000000      118.750000   8684.800000

In [13]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [19]:
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
df.corr()

SeniorCitizen    tenure  MonthlyCharges  TotalCharges
SeniorCitizen        1.000000  0.015683        0.219874      0.102411
tenure               0.015683  1.000000        0.246862      0.825880
MonthlyCharges       0.219874  0.246862        1.000000      0.651065
TotalCharges         0.102411  0.825880        0.651065      1.000000

In [133]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [134]:
x = df.loc[:,['MonthlyCharges','tenure']].values
x

array([[ 29.85,   1.  ],
       [ 56.95,  34.  ],
       [ 53.85,   2.  ],
       ...,
       [ 29.6 ,  11.  ],
       [ 74.4 ,   4.  ],
       [105.65,  66.  ]])

In [137]:
#df['TotalCharges'] = df['TotalCharges'].astype(float)
y = df.loc[:, ['TotalCharges']].values
y

array([[  29.85],
       [1889.5 ],
       [ 108.15],
       ...,
       [ 346.45],
       [ 306.6 ],
       [6844.5 ]])

In [138]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.30, random_state=0)

In [139]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((4922, 2), (2110, 2), (4922, 1), (2110, 1))

In [140]:
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [141]:
y_pred = regressor.predict(x_test)
y_pred, y_test

(array([[-1350.73879297],
        [ -365.21108083],
        [-1380.95603098],
        ...,
        [ 3053.90669946],
        [ 3416.71248806],
        [ 2651.85994828]]),
 array([[  20.65],
        [ 330.25],
        [  19.8 ],
        ...,
        [2815.25],
        [1623.15],
        [1296.15]]))

In [142]:
from sklearn.metrics import r2_score

In [147]:
r2 = r2_score(y_test, y_pred)*100
print(f'R2 Value is : {r2}')

R2 Value is : 89.05146634490715


In [145]:
from Adjustedr2 import adjusted_r2

Enter the R2 Value: 89.05
Enter the Number of Observations: 4922
Enter the Number of Independent Variable: 2
Adjusted R2 is:  89.08579995934133


In [21]:
from sklearn import metrics
print(dir(metrics))

['ConfusionMatrixDisplay', 'PrecisionRecallDisplay', 'RocCurveDisplay', 'SCORERS', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_base', '_classification', '_pairwise_fast', '_plot', '_ranking', '_regression', '_scorer', 'accuracy_score', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'auc', 'average_precision_score', 'balanced_accuracy_score', 'brier_score_loss', 'calinski_harabasz_score', 'check_scoring', 'classification_report', 'cluster', 'cohen_kappa_score', 'completeness_score', 'confusion_matrix', 'consensus_score', 'coverage_error', 'davies_bouldin_score', 'dcg_score', 'euclidean_distances', 'explained_variance_score', 'f1_score', 'fbeta_score', 'fowlkes_mallows_score', 'get_scorer', 'hamming_loss', 'hinge_loss', 'homogeneity_completeness_v_measure', 'homogeneity_score', 'jaccard_score', 'label_ranking_average_precision_score', 'label_ranking_loss', 'log_loss', 'make_scorer', 'matthews_cor

## Logistic Regression

In [162]:
# df['gender']= pd.get_dummies(df['gender'])
# df['Partner']= pd.get_dummies(df[ 'Partner'])
# df['Dependents']= pd.get_dummies(df['Dependents'])
# df['PhoneService']= pd.get_dummies(df['PhoneService'])

In [25]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges  Churn  
0           Electronic check          29.85         29.85     No  
1               Mailed check          56.95       1889.50     No  
2               Mailed check          53.85        108.15    Yes  
3  Bank transfer (automatic)          42.30       1840.75     No  
4           Electronic check          70.70        151.65    Yes  

[5 rows x 21 columns]

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7032 non-null   object 
 1   gender            7032 non-null   object 
 2   SeniorCitizen     7032 non-null   int64  
 3   Partner           7032 non-null   object 
 4   Dependents        7032 non-null   object 
 5   tenure            7032 non-null   int64  
 6   PhoneService      7032 non-null   object 
 7   MultipleLines     7032 non-null   object 
 8   InternetService   7032 non-null   object 
 9   OnlineSecurity    7032 non-null   object 
 10  OnlineBackup      7032 non-null   object 
 11  DeviceProtection  7032 non-null   object 
 12  TechSupport       7032 non-null   object 
 13  StreamingTV       7032 non-null   object 
 14  StreamingMovies   7032 non-null   object 
 15  Contract          7032 non-null   object 
 16  PaperlessBilling  7032 non-null   object 


In [27]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [28]:
x = df[['MonthlyCharges', 'TotalCharges']].values
x

array([[  29.85,   29.85],
       [  56.95, 1889.5 ],
       [  53.85,  108.15],
       ...,
       [  29.6 ,  346.45],
       [  74.4 ,  306.6 ],
       [ 105.65, 6844.5 ]])

In [29]:
df['Churn'] = pd.get_dummies(df['Churn'])

In [30]:
y = df.iloc[:,20].values
y.reshape(1,-1)

array([[1, 1, 0, ..., 1, 0, 1]], dtype=uint8)

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
regressor = LogisticRegression()
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.30, random_state=0)

<IPython.core.display.Javascript object>

In [33]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((4922, 2), (2110, 2), (4922,), (2110,))

In [34]:
regressor.fit(x_train, y_train)

LogisticRegression()

In [35]:
y_pred = regressor.predict(x_test)
y_pred, y_test

(array([1, 1, 1, ..., 1, 1, 1], dtype=uint8),
 array([1, 1, 1, ..., 1, 1, 1], dtype=uint8))

In [40]:
y_pred_train = regressor.predict(x_train)
y_pred_train

array([1, 1, 0, ..., 1, 0, 1], dtype=uint8)

In [41]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, plot_roc_curve

In [42]:
cm = confusion_matrix(y_test, y_pred)
print(f'LR Confusion Matrix: ', cm)

a = accuracy_score(y_train, y_pred_train)*100
print(f'LR Accuracy Score of train is: {a}')

b = roc_auc_score(y_train, y_pred_train)*100
print(f'LR Roc AUC Score of train is: {b}')

c = accuracy_score(y_test, y_pred)*100
print(f'LR Accuracy Score of test is: {c}')

d = roc_auc_score(y_test, y_pred)*100
print(f'LR Roc AUC Score of test is: {d}')

LR Confusion Matrix:  [[ 241  314]
 [ 150 1405]]
LR Accuracy Score of train is: 78.76879317350671
LR Roc AUC Score of train is: 68.14724677446027
LR Accuracy Score of test is: 78.00947867298578
LR Roc AUC Score of test is: 66.88856058630978


# Decission Tree

In [227]:
df.head()

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0  7590-VHVEG       1              0        0           1       1   
1  5575-GNVDE       0              0        1           1      34   
2  3668-QPYBK       0              0        1           1       2   
3  7795-CFOCW       0              0        1           1      45   
4  9237-HQITU       1              0        1           1       2   

   PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0             1  No phone service             DSL             No  ...   
1             0                No             DSL            Yes  ...   
2             0                No             DSL            Yes  ...   
3             1  No phone service             DSL            Yes  ...   
4             0                No     Fiber optic             No  ...   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0              Yes           Electronic check          29.85         29.85   
1               No               Mailed check          56.95       1889.50   
2              Yes               Mailed check          53.85        108.15   
3               No  Bank transfer (automatic)          42.30       1840.75   
4              Yes           Electronic check          70.70        151.65   

   Churn  
0      1  
1      1  
2      0  
3      1  
4      0  

[5 rows x 21 columns]

In [228]:
x = df[['MonthlyCharges', 'TotalCharges']].values
x

array([[  29.85,   29.85],
       [  56.95, 1889.5 ],
       [  53.85,  108.15],
       ...,
       [  29.6 ,  346.45],
       [  74.4 ,  306.6 ],
       [ 105.65, 6844.5 ]])

In [231]:
y = df.loc[:,['Churn']].values
y

array([[1],
       [1],
       [0],
       ...,
       [1],
       [0],
       [1]], dtype=uint8)

In [232]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.30, random_state=0)

In [233]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((4922, 2), (2110, 2), (4922, 1), (2110, 1))

In [234]:
from sklearn.tree import DecisionTreeClassifier

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [246]:
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0, 
    max_depth=2,
    min_samples_split=20,
    min_samples_leaf=40)

classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=2, min_samples_leaf=40,
                       min_samples_split=20, random_state=0)

In [247]:
y_pred = classifier.predict(x_test)
y_pred_train = classifier.predict(x_train)
y_pred, y_pred_train

(array([1, 1, 1, ..., 1, 1, 1], dtype=uint8),
 array([1, 1, 0, ..., 1, 0, 1], dtype=uint8))

In [248]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, plot_roc_curve

In [271]:
cm = confusion_matrix(y_test, y_pred)
print(f'DT Confusion Matrix: ', cm)

a = accuracy_score(y_train, y_pred_train)*100
print(f'DT Accuracy Score of train is: {a}')

b = roc_auc_score(y_train, y_pred_train)*100
print(f'DT Roc AUC Score of train is: {b}')

c = accuracy_score(y_test, y_pred)*100
print(f'DT Accuracy Score of test is: {c}')

d = roc_auc_score(y_test, y_pred)*100
print(f'DT Roc AUC Score of test is: {d}')


DT Confusion Matrix:  [[ 252  303]
 [ 214 1341]]
DT Accuracy Score of train is: 98.94351889475823
DT Roc AUC Score of train is: 98.48098846804159
DT Accuracy Score of test is: 75.49763033175356
DT Roc AUC Score of test is: 65.82167376379596


# Random Forest

In [286]:
x = df[['MonthlyCharges', 'TotalCharges']].values
x

array([[  29.85,   29.85],
       [  56.95, 1889.5 ],
       [  53.85,  108.15],
       ...,
       [  29.6 ,  346.45],
       [  74.4 ,  306.6 ],
       [ 105.65, 6844.5 ]])

In [287]:
y = df.loc[:,['Churn']].values
y

array([[1],
       [1],
       [0],
       ...,
       [1],
       [0],
       [1]], dtype=uint8)

In [288]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.30, random_state=0)

In [289]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((4922, 2), (2110, 2), (4922, 1), (2110, 1))

In [290]:
from sklearn.ensemble import RandomForestClassifier


In [291]:
classifier = RandomForestClassifier(n_estimators = 50, criterion = 'gini', random_state = 0,
                                    
   
    max_features=2, n_jobs=-1)
classifier.fit(x_train, y_train)

<ipython-input-291-2a90f7827371>:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(x_train, y_train)


RandomForestClassifier(max_features=2, n_estimators=50, n_jobs=-1,
                       random_state=0)

In [292]:
y_pred = classifier.predict(x_test)
y_pred_train = classifier.predict(x_train)
y_pred, y_pred_train

(array([1, 1, 0, ..., 1, 1, 1], dtype=uint8),
 array([1, 1, 1, ..., 0, 1, 1], dtype=uint8))

In [293]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, plot_roc_curve

In [294]:
cm = confusion_matrix(y_test, y_pred)
print(f'RF - Confusion Matrix is : ', cm)

a = accuracy_score(y_train, y_pred_train)*100
print(f'RF - Accuracy Score of train is: {a}')

b = roc_auc_score(y_train, y_pred_train)*100
print(f'RF - Roc AUC Score of train is: {b}')

c = accuracy_score(y_test, y_pred)*100
print(f'RF - Accuracy Score of test is: {c}')

d = roc_auc_score(y_test, y_pred)*100
print(f'RF - Roc AUC Score of test is: {d}')


RF - Confusion Matrix is :  [[ 252  303]
 [ 214 1341]]
RF - Accuracy Score of train is: 98.94351889475823
RF - Roc AUC Score of train is: 98.48098846804159
RF - Accuracy Score of test is: 75.49763033175356
RF - Roc AUC Score of test is: 65.82167376379596
