In [12]:
myList = [10,20,30,'apple', True, 8.10]

In [14]:
myList.append(30)
myList.append(40)

In [15]:
myList

[10, 20, 30, 'apple', True, 8.1, 30, 40]

In [21]:
reversedList = myList[::-1]
reversedList

[40, 30, 8.1, True, 'apple', 30, 20, 10]

In [77]:
dic = {1:'data', 2:'information', 3: 'text'}

In [78]:
dic

{1: 'data', 2: 'information', 3: 'text'}

In [79]:
dic[3] = 'features'
dic

{1: 'data', 2: 'information', 3: 'features'}

In [101]:
my_tuple = (1,2,3,'apple','mango')
my_tuple

(1, 2, 3, 'apple', 'mango')

In [102]:
numeric_tuple = (10,20,30,40,50)
numeric_tuple

(10, 20, 30, 40, 50)

In [103]:
r1 = my_tuple+numeric_tuple
r1

(1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)

In [104]:
newdupli = my_tuple * 2

In [105]:
newdupli

(1, 2, 3, 'apple', 'mango', 1, 2, 3, 'apple', 'mango')

In [92]:
set1 = {1,2,3,4,5}

In [93]:
set1

{1, 2, 3, 4, 5}

In [94]:
set2 = {2,3,7,6,1}

In [95]:
set2

{1, 2, 3, 6, 7}

In [109]:
set1.union(set2)

{1, 2, 3, 4, 5, 6, 7}

In [110]:
set1.intersection(set2)

{1, 2, 3}

In [111]:
set1.difference(set2)

{4, 5}

## Module 4:Numpy Assignment

1. Create a 3x3 matrix array with values ranging from 2 to 10.

In [112]:
import numpy as np

In [119]:
np_array = np.arange(2,11)
np_array.resize(3,3)
np_array

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [126]:
n = int(input('Enter the values for array: '))

array1 = np.arange(1, n)
array1

Enter the values for array: 7


array([1, 2, 3, 4, 5, 6])

In [129]:
array2 = array1.astype(float)
array2

array([1., 2., 3., 4., 5., 6.])

In [130]:
arr = np.array([10, 20, 30])

In [131]:
arr

array([10, 20, 30])

In [144]:
arr1 = ([40,50,60,70,80,90])

np.concatenate([arr,arr1])

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [146]:
arr3 = np.array([1,2,3,4,5])

In [147]:
arr3

array([1, 2, 3, 4, 5])

In [148]:
arr4 = np.array([6,7,8,9,10])

In [149]:
arr4

array([ 6,  7,  8,  9, 10])

In [150]:
np.add(arr3, arr4)

array([ 7,  9, 11, 13, 15])

In [ ]:
5.Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. 
Perform the following tasks:
    a.Extract the 1strow from the array.
    b.Extract the last element from the array.

In [154]:
array1 = np.arange(10,91,10)
array1.resize(3,3)

In [155]:
array1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [156]:
array1[0:1,]

array([[10, 20, 30]])

In [170]:
array1[2:,2:]

array([[90]])