# Linear Regression Assignment

In [1]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv("Salary.csv")
df.head(2)

Experience  Salary
0         1.1   39343
1         1.3   46205

In [7]:
x = df.iloc[:,0].values.reshape(-1,1)
y = df.iloc[:,1].values.reshape(-1,1)
x, y

(array([[ 1.1],
        [ 1.3],
        [ 1.5],
        [ 2. ],
        [ 2.2],
        [ 2.9],
        [ 3. ],
        [ 3.2],
        [ 3.2],
        [ 3.7],
        [ 3.9],
        [ 4. ],
        [ 4. ],
        [ 4.1],
        [ 4.5],
        [ 4.9],
        [ 5.1],
        [ 5.3],
        [ 5.9],
        [ 6. ],
        [ 6.8],
        [ 7.1],
        [ 7.9],
        [ 8.2],
        [ 8.7],
        [ 9. ],
        [ 9.5],
        [ 9.6],
        [10.3],
        [10.5]]),
 array([[ 39343],
        [ 46205],
        [ 37731],
        [ 43525],
        [ 39891],
        [ 56642],
        [ 60150],
        [ 54445],
        [ 64445],
        [ 57189],
        [ 63218],
        [ 55794],
        [ 56957],
        [ 57081],
        [ 61111],
        [ 67938],
        [ 66029],
        [ 83088],
        [ 81363],
        [ 93940],
        [ 91738],
        [ 98273],
        [101301],
        [113812],
        [109431],
        [105582],
        [116969],
        [112635],
        [12239

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.33, random_state=0)

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [12]:
y_predict = regressor.predict(x_test)

In [13]:
y_predict

array([[ 40835.10590871],
       [123079.39940819],
       [ 65134.55626083],
       [ 63265.36777221],
       [115602.64545369],
       [108125.8914992 ],
       [116537.23969801],
       [ 64199.96201652],
       [ 76349.68719258],
       [100649.1375447 ]])

In [14]:
from sklearn.metrics import r2_score

In [15]:
r2_score(y_test, y_predict)*100

97.49155046280816